// Curated imposter hints — RELATED WORD pairs (spec: a hint must be a related
// word like "water" for "sponge", never "starts with S" or "found in the
// kitchen"). Curated pairs aim for a *far/loose* association: enough to spark
// an idea, never enough to give the word away.
//
// Words without a curated pair fall back to a seeded pick from the same
// category's pool (see hints.js) — still a related word, never the word itself.
//
// Every key is a normalized word id that exists in WORD_DB (enforced by
// tests/hints.test.js). 977 curated pairs.

export const HINTS = Object.freeze({
  // food
  "dosa": "griddle",
  "idli": "steam",
  "samosa": "triangle",
  "pizza": "cheesy slice",
  "burger": "bun",
  "biryani": "spices",
  "ice cream": "summer",
  "chocolate": "cocoa",
  "mango": "summer king",
  "banana": "peel",
  "apple": "orchard",
  "grapes": "vineyard",
  "lemonade": "sour",
  "milk": "glass",
  "tea": "leaf",
  "coffee": "bean",
  "honey": "bee",
  "bread": "crumbs",
  "butter": "melt",
  "cheese": "melt",
  "egg": "shell",
  "rice": "paddy",
  "curd": "probiotic",
  "laddu": "round sweet",
  "jalebi": "syrup",
  "kulfi": "stick",
  "pasta": "spaghetti",
  "noodles": "slurp",
  "popcorn": "cinema",
  "cake": "birthday",
  "biscuit": "tea time",
  "pudding": "wobble",
  "pancake": "maple",
  "omelette": "whisk",
  "soup": "bowl",
  "salad": "garden",
  "puri": "puff",
  "paratha": "ghee",
  "vada": "medu",
  "poha": "flattened rice",
  "upma": "semolina",
  "puliyodarai": "tamarind",
  "palak paneer": "green cheese",
  "butter chicken": "tandoor",
  "gulab jamun": "syrup ball",
  "kheer": "rice dessert",
  "coconut water": "tender",
  "pani puri": "street cart",
  "pav bhaji": "mumbai",
  "filter coffee": "dabara",
  "masala chai": "spiced boil",
  "momos": "steamer basket",
  "falooda": "rose syrup",
  "lassi": "blended curd",
  "kokum": "sherbet",
  "pongal": "sugarcane",
  "sherbet": "summer cool",
  "orange": "sunset fruit",
  // animals
  "dog": "loyal",
  "cat": "whiskers",
  "cow": "moo",
  "elephant": "trunk",
  "tiger": "stripes",
  "lion": "mane",
  "monkey": "banana thief",
  "rabbit": "carrot",
  "horse": "saddle",
  "camel": "desert ship",
  "peacock": "feather fan",
  "parrot": "mimic",
  "owl": "night hoot",
  "crow": "caw",
  "sparrow": "chirp",
  "fish": "gills",
  "snake": "slither",
  "frog": "croak",
  "butterfly": "cocoon",
  "ant": "picnic line",
  "spider": "web",
  "sheep": "wool",
  "leopard": "spots",
  "deer": "graceful jump",
  "squirrel": "nut hoarder",
  "fox": "clever",
  "wolf": "pack howl",
  "eagle": "sharp eyes",
  "penguin": "waddle",
  "dolphin": "clicks",
  "whale": "ocean giant",
  "turtle": "shell",
  "honeybee": "hive",
  "zebra": "crossing",
  "giraffe": "neck",
  "kangaroo": "pouch",
  "crocodile": "river teeth",
  "mongoose": "snake duel",
  "hippopotamus": "river horse",
  "woodpecker": "drum beak",
  "ostrich": "buried head",
  "bat": "echo",
  "panda": "bamboo",
  "koala": "eucalyptus",
  "cheetah": "sprint",
  "hyena": "laugh",
  "vulture": "circle",
  "flamingo": "pink stand",
  // nature
  "sun": "dawn",
  "moon": "tide",
  "star": "pointed sky",
  "cloud": "remote rack",
  "rain": "petrichor",
  "rainbow": "seven bands",
  "wind": "whoosh",
  "river": "flow",
  "lake": "still water",
  "sea": "salt",
  "ocean": "wave",
  "tree": "canopy",
  "flower": "pollen",
  "grass": "dew",
  "leaf": "chlorophyll",
  "sand": "grain",
  "rock": "boulder",
  "sunrise": "horizon",
  "sunset": "orange sky",
  "shadow": "noon",
  "mountain": "peak",
  "thunder": "rumble",
  "lightning": "flash",
  "storm": "shutters",
  "snow": "avalanche",
  "pond": "lily",
  "waterfall": "mist",
  "hill": "trek",
  "valley": "between slopes",
  "forest": "canopy shade",
  "root": "soil grip",
  "seed": "sprout",
  "soil": "worm",
  "desert": "oasis",
  "island": "surrounded",
  "fog": "low cloud",
  "mist": "hills",
  "volcano": "lava",
  "earthquake": "tremor",
  "flood": "sandbags",
  "drought": "cracked earth",
  "eclipse": "alignment",
  "glacier": "ice river",
  "banyan tree": "hanging roots",
  "sunflower": "heliotrope",
  // colours
  "rose": "thorn",
  "coral": "reef",
  "triangle": "three sides",
  "red": "alarm",
  "blue": "sky deep",
  "green": "leaf chlorophyll",
  "yellow": "sunflower",
  "black": "midnight",
  "white": "chalk",
  "pink": "blossom",
  "purple": "brinjal",
  "gold": "medal shine",
  "silver": "moon metal",
  "circle": "no corners",
  "square": "four equal sides",
  "heart": "valentine",
  "spiral": "snail shell",
  "diamond": "kite shape",
  "cube": "six faces",
  "sphere": "perfect round",
  "cylinder": "rolled sheet",
  "cone": "ice cream scoop",
  "crescent": "moon sliver",
  // household
  "chair": "four legs",
  "table": "spread",
  "sofa": "cushion sink",
  "bed": "blanket",
  "pillow": "fluff",
  "blanket": "wool",
  "fan": "blade spin",
  "light bulb": "glow coil",
  "clock": "hands",
  "mirror": "silvered glass",
  "door": "knob",
  "window": "sill",
  "key": "teeth",
  "lock": "bolt",
  "bucket": "handle",
  "mug": "sip",
  "bottle": "cap",
  "towel": "dry",
  "soap": "lather",
  "toothbrush": "bristles",
  "toothpaste": "mint",
  "comb": "teeth",
  "umbrella": "canopy",
  "candle": "wick",
  "scissors": "blades",
  "tape": "roll",
  "calendar": "dates",
  "dustbin": "lid",
  "doormat": "welcome",
  "curtain": "drape",
  "stool": "step",
  "drawer": "pull",
  "photo album": "flip",
  "backpack": "straps",
  "pencil": "shavings",
  "notebook": "margin line",
  // tools
  "ladder": "step climb",
  "hammer": "nail head",
  "axe": "chop",
  "shovel": "dig lever",
  "screwdriver": "rotation",
  "wrench": "bolt grip",
  "pliers": "wire twist",
  "drill": "bit spin",
  "saw": "tooth line",
  "measuring tape": "retract click",
  "paintbrush": "bristles",
  "crowbar": "pry",
  "chisel": "mallet pair",
  "clamp": "grip vise",
  "trowel": "cement swipe",
  "spirit level": "bubble",
  "stapler": "thunk",
  "glue gun": "hot string",
  "sandpaper": "grit",
  // clothing
  "shirt": "collar",
  "t-shirt": "crew neck",
  "jeans": "denim",
  "dress": "hemline",
  "saree": "drape",
  "kurta": "festive",
  "shoes": "sole",
  "sandals": "strap",
  "cap": "brim",
  "belt": "buckle",
  "watch": "strap tick",
  "sunglasses": "uv",
  "raincoat": "monsoon",
  "jacket": "zipper",
  "sweater": "knit",
  "ring": "band",
  "necklace": "pendant",
  "earrings": "dangle",
  "handbag": "clutch",
  "scarf": "wrap",
  "tie": "knot",
  "helmet": "strap chin",
  "gloves": "fingers",
  "socks": "pair",
  "shorts": "summer",
  "skirt": "pleat",
  "hoodie": "kangaroo pocket",
  "face mask": "ear loops",
  // school
  "uniform": "tie knot",
  "classroom": "benches",
  "blackboard": "chalk dust",
  "chalk": "squeak",
  "textbook": "chapters",
  "homework": "deadline",
  "library": "shelves",
  "whiteboard": "marker",
  "exam paper": "blue book",
  "report card": "grades",
  "timetable": "periods",
  "laboratory": "apron",
  "microscope": "slide",
  "calculator": "digits",
  "ruler": "centimetres",
  "certificate": "seal",
  "geometry box": "compass",
  "ink pen": "fountain",
  "attendance register": "roll call",
  "eraser": "rubber",
  "project": "chart paper",
  "student": "desk",
  "principal": "office",
  "playground": "swings",
  "reading": "bookmark",
  // technology
  "button": "thread",
  "smartphone": "swipe",
  "laptop": "hinge",
  "mouse": "click pad",
  "monitor": "pixels",
  "television": "channel surf",
  "remote control": "buttons",
  "headphones": "bass",
  "charger": "cable",
  "tablet": "tap",
  "email": "inbox",
  "app": "icon",
  "video call": "buffering",
  "qr code": "scan",
  "screenshot": "capture",
  "keyboard": "qwerty",
  "scanner": "flatbed",
  "webcam": "lens light",
  "microphone": "pop filter",
  "power bank": "mah",
  "usb cable": "port",
  "wi-fi router": "signal bars",
  "bluetooth speaker": "pairing",
  "smartwatch": "step count",
  "flash drive": "plug",
  "memory card": "slot",
  "browser": "tabs",
  "server": "rack",
  "password": "asterisks",
  "download": "progress bar",
  "upload": "cloud arrow",
  "website": "address bar",
  "drone": "propellers",
  "motherboard": "circuits",
  "robot vacuum": "dust roamer",
  // sports
  "cricket": "crease",
  "football": "goal net",
  "badminton": "smash",
  "volleyball": "spike",
  "basketball": "dribble",
  "tennis": "deuce",
  "hockey": "dribble",
  "kabaddi": "raid",
  "kho-kho": "chase",
  "chess": "checkmate",
  "carrom": "striker",
  "ludo": "dice cup",
  "running": "track lane",
  "swimming": "lane rope",
  "cycling": "gear shift",
  "archery": "bullseye",
  "boxing": "gong",
  "wrestling": "mat",
  "golf": "putt",
  "baseball": "home run",
  "skating": "blade",
  "marathon": "hydration",
  "relay": "baton",
  "gymnastics": "beam",
  "wicket": "stumps",
  "whistle": "peep",
  "referee": "flag",
  // people
  "printer": "cartridge",
  "teacher": "red pen",
  "doctor": "white coat",
  "police officer": "law and order",
  "farmer": "rice fields",
  "driver": "steering wheel",
  "chef": "tasting spoon",
  "nurse": "night rounds",
  "singer": "high notes",
  "actor": "stage lights",
  "shopkeeper": "cash box",
  "banker": "vault",
  "accountant": "ledger books",
  "waiter": "order pad",
  "cook": "hot stove",
  "baker": "fresh loaf",
  "cobbler": "shoe repair",
  "weaver": "loom threads",
  "potter": "spinning clay",
  "sculptor": "chisel",
  "painter": "wet canvas",
  "dancer": "rhythm steps",
  "musician": "melody",
  "composer": "written score",
  "magician": "sleight of hand",
  "jockey": "gallop",
  "athlete": "finish line",
  "coach": "training drill",
  "commentator": "live mic",
  "newsreader": "evening bulletin",
  "editor": "red marks",
  "writer": "blank page",
  "poet": "rhyme",
  "novelist": "long chapters",
  "librarian": "quiet shelves",
  "historian": "dust archives",
  "geographer": "atlas",
  "psychologist": "couch sessions",
  "pharmacist": "pill counter",
  "paramedic": "siren rush",
  "midwife": "newborn cry",
  "optician": "letter chart",
  "therapist": "calm voice",
  "counsellor": "listening chair",
  "social worker": "home visits",
  "volunteer": "unpaid kindness",
  "constable": "beat patrol",
  "traffic police": "whistle signals",
  "commando": "night raid",
  "sailor": "ship deck",
  "lifeguard": "rescue tube",
  "bodyguard": "dark glasses",
  "detective": "magnifying glass",
  "spy": "trench coat",
  "clerk": "rubber stamp",
  "typist": "clacking keys",
  "receptionist": "front desk",
  "secretary": "meeting notes",
  "janitor": "mop bucket",
  "housekeeper": "tidy rooms",
  "maid": "folded towels",
  "gardener": "pruning shears",
  "tutor": "home lessons",
  "scholar": "library lamp",
  "technician": "toolkit",
  "welder": "sparking arc",
  "fitter": "pipe wrench",
  "mason": "brick mortar",
  "blacksmith": "hot anvil",
  "goldsmith": "delicate chains",
  "locksmith": "tiny pins",
  "watchmaker": "tiny gears",
  "jeweller": "gem tray",
  "trader": "market calls",
  "merchant": "silk route",
  "salesperson": "elevator pitch",
  "assistant": "right hand",
  "porter": "heavy luggage",
  "postman": "letters",
  "courier": "parcel bag",
  "sanitation worker": "clean streets",
  "astronaut": "rocket launch",
  "flight attendant": "cabin safety",
  "beekeeper": "smoke veil",
  "shepherd": "hill flock",
  "fisherman": "nets",
  "ranger": "forest patrol",
  "zookeeper": "feeding time",
  "businessperson": "briefcase deals",
  "entrepreneur": "startup risk",
  "manager": "team targets",
  "auditor": "receipt trail",
  "consultant": "expert advice",
  "advocate": "court arguments",
  "grid operator": "power lines",
  "traffic warden": "parking fines",
  "switchboard operator": "plug cords",
  "toll collector": "boom barrier",
  "engineer": "blueprint maths",
  "firefighter": "ladder truck",
  "tailor": "needle thread",
  "barber": "sharp scissors",
  "electrician": "live wires",
  "plumber": "leaky taps",
  "mechanic": "grease",
  "dentist": "molar ache",
  "pilot": "cockpit",
  "soldier": "boot camp",
  "scientist": "lab notes",
  "artist": "colour palette",
  "photographer": "golden hour",
  "carpenter": "sawdust",
  "architect": "scale model",
  "lawyer": "case files",
  "judge": "wooden gavel",
  "journalist": "press pass",
  "software developer": "keyboard bugs",
  "delivery worker": "doorbell rush",
  "security guard": "night gate",
  "cashier": "till counter",
  "chartered accountant": "tax season",
  "bus conductor": "ticket bell",
  "surgeon": "operating theatre",
  "civil engineer": "site plans",
  "mechanical engineer": "moving parts",
  "electrical engineer": "circuit design",
  "chemical engineer": "reactor maths",
  "robotics engineer": "servo arms",
  "network engineer": "cable racks",
  "hardware engineer": "motherboard",
  "data analyst": "spreadsheet charts",
  "data scientist": "pattern mining",
  "web designer": "layout grids",
  "graphic designer": "logo sketches",
  "ux designer": "user journeys",
  "game developer": "level design",
  "quality analyst": "bug reports",
  "hacker": "keyboard break in",
  "museum curator": "old collections",
  "translator": "two tongues",
  "proofreader": "comma hunt",
  "copywriter": "catchy lines",
  "screenwriter": "scene dialogue",
  "playwright": "stage acts",
  "glassblower": "hot furnace",
  "bank teller": "cash drawer",
  "loan officer": "emi approvals",
  "insurance agent": "policy papers",
  "real estate agent": "site visits",
  "auctioneer": "going once",
  "actuary": "risk tables",
  "statistician": "survey curves",
  "economist": "market cycles",
  "radiographer": "x ray films",
  "pathologist": "lab samples",
  "anaesthetist": "count backwards",
  "paediatrician": "little patients",
  "cardiologist": "heart rhythms",
  "dermatologist": "rash charts",
  "neurologist": "nerve maps",
  "oncologist": "cancer care",
  "orthopaedic surgeon": "bone setting",
  "psychiatrist": "deep sessions",
  "physiotherapist": "stretch routines",
  "dietitian": "meal plans",
  "dog trainer": "fetch commands",
  "yoga teacher": "morning poses",
  "bartender": "cocktail shaker",
  "barista": "latte art",
  "pastry chef": "oven sweets",
  "chocolatier": "melted cocoa",
  "wedding planner": "big fat functions",
  "astronomer": "star charts",
  "veterinarian": "animal clinic",
  "anthropologist": "human tribes",
  "archaeologist": "old dig sites",
  "epigraphist": "stone inscriptions",
  "numismatist": "coin collections",
  "philatelist": "stamp albums",
  "etymologist": "word origins",
  "lexicographer": "dictionary making",
  "paleontologist": "dinosaur bones",
  "geologist": "rock layers",
  "seismologist": "tremor graphs",
  "volcanologist": "lava fieldwork",
  "meteorologist": "weather balloon",
  "oceanographer": "deep currents",
  "ecologist": "food webs",
  "botanist": "plant press",
  "zoologist": "species notes",
  "entomologist": "bug jars",
  "ornithologist": "bird calls",
  "herpetologist": "snake catching",
  "microbiologist": "petri dishes",
  "mycologist": "fungi forays",
  "virologist": "virus cultures",
  "immunologist": "antibody studies",
  "geneticist": "dna ladder",
  "biochemist": "cell reactions",
  "pharmacologist": "drug trials",
  "epidemiologist": "outbreak maps",
  "neuroscientist": "brain imaging",
  "astrophysicist": "cosmic maths",
  "cryptographer": "cipher wheels",
  "air traffic controller": "radar screens",
  "test pilot": "prototype jets",
  "forensic analyst": "crime labs",
  "fingerprint expert": "ridge patterns",
  // special
  "algorithm": "recipe steps",
  "database": "indexed rows",
  "encryption": "scrambled eggs",
  "firewall": "packet gatekeeper",
  "chatbot": "typing dots",
  "virtual reality": "headset",
  "vr developments": "a great brand",
  "artificial intelligence": "pattern learner",
  "robotics": "servo joint",
  "cloud computing": "remote rack",
  "bandwidth": "pipe width",
  "processor": "clock ticks",
  "microchip": "wafer etched",
  "firmware": "burned in",
  "machine learning": "training curves",
  "neural network": "layered nodes",
  "prompt engineering": "careful wording",
  "automation": "conveyor arms",
  "large language model": "next word guess",
  "hallucination": "confident nonsense",
  "training data": "labelled examples",
  "cyber security": "locked ports",
  "data bias": "tilted sample",
  "computer vision": "pixel recogniser",
  "natural language processing": "sentence parse",
  "deep learning": "stacked layers",
  "generative ai": "fresh artefacts",
  "predictive text": "next word bar",
  "internet of things": "sensor swarm",
  "blockchain": "linked ledger",
  "quantum computing": "qubit spin",
  "augmented reality": "overlay lens",
  "3d printing": "layer by layer",
  "smart home": "voice lights",
  "big data": "warehouse of rows",
  "api": "menu for programs",
  "debugging": "bug hunt",
  "open source": "public blueprint",
  "version control": "commit history",
  "robot arm": "assembly line",
  "smart speaker": "voice answers",
  "voice remote": "talk to tv",
  "smart display": "kitchen screen",
  "robot mop": "wet floors",
  "pet robot": "electronic puppy",
  "toy ai": "chatty playmate",
  "chat friend": "never sleeps",
  "story app": "bedtime tales",
  "maths app": "sum practice",
  "spelling app": "dictation practice",
  "drawing app": "finger canvas",
  "music app": "playlist",
  "video app": "endless shorts",
  "game app": "level ups",
  "learning app": "daily lessons",
  "quiz app": "quick questions",
  "map app": "blue dot",
  "pay app": "scan and pay",
  "bank app": "balance check",
  "bus app": "next stop",
  "train app": "platform status",
  "food delivery app": "doorstep meals",
  "shopping app": "cart checkout",
  "health app": "step goals",
  "fitness app": "workout streaks",
  "sleep app": "dream cycles",
  "meditation app": "calm breathing",
  "language app": "daily streak",
  "translation app": "two languages",
  "photo editor app": "crop filters",
  "keyboard app": "swipe typing",
  "reminder app": "gentle nudges",
  "alarm app": "wake rings",
  "flashlight app": "torch beam",
  "qr scanner app": "square codes",
  "password app": "secret vault",
  "step counter app": "morning walks",
  "heart rate app": "pulse checks",
  // festivals
  "sports day": "track events",
  "diwali": "diyas",
  "holi": "colours",
  "eid": "new moon",
  "christmas": "stocking",
  "birthday": "candles to blow",
  "wedding": "mandap",
  "new year": "countdown",
  "onam": "floral carpet",
  "navratri": "garba circles",
  "dussehra": "effigy",
  "ganesh chaturthi": "modak",
  "raksha bandhan": "wrist thread",
  "sankranti": "kite sky",
  "ugadi": "neem jaggery",
  "baisakhi": "bhangra",
  "gudi padwa": "flag raise",
  "graduation": "cap toss",
  "anniversary": "bouquet",
  "picnic": "basket",
  "celebration": "confetti",
  "housewarming": "threshold decor",
  "farewell": "memory book",
  "reunion": "old friends",
  "baby shower": "games",
  "engagement": "ring exchange",
  "kite festival": "manja",
  // places
  "hospital": "wards",
  "park": "fountain",
  "temple": "bells",
  "beach": "shells",
  "city": "skyline",
  "village": "wells",
  "office": "cubicle",
  "bank": "vault",
  "cinema": "popcorn smell",
  "zoo": "enclosures",
  "bus stop": "shelter",
  "restaurant": "menu card",
  "hotel": "reception bell",
  "apartment": "lift button",
  "college": "campus",
  "clinic": "waiting room",
  "pharmacy": "shelves of strips",
  "supermarket": "aisles",
  "shopping mall": "escalator",
  "railway station": "platform announcement",
  "airport": "check-in counter",
  "museum": "exhibits",
  "stadium": "floodlights",
  "mosque": "minaret",
  "church": "steeple",
  "factory": "assembly line",
  "police station": "wireless",
  "fire station": "pole",
  "post office": "stamps",
  "petrol station": "nozzle",
  "town hall": "civic",
  "monastery": "chants",
  "gym": "weights",
  "garden": "blossoms",
  // transport
  "auto-rickshaw": "meter",
  "bicycle": "bell ring",
  "motorcycle": "kickstand",
  "scooter": "floorboard",
  "car": "steering wheel",
  "bus": "conductor bell",
  "train": "platform whistle",
  "airplane": "cabin pressure",
  "boat": "oars",
  "ship": "anchor",
  "truck": "cargo bed",
  "tractor": "mud tyres",
  "ambulance": "siren wail",
  "fire engine": "ladder on top",
  "taxi": "flag down",
  "metro train": "smart gate",
  "helicopter": "rotor wash",
  "rickshaw": "hood",
  "ferry": "ramp",
  "bullock cart": "yoke",
  "jeep": "hill road",
  "train engine": "coupling",
  "hovercraft": "air cushion",
  "submarine": "periscope",
  "glider": "thermal",
  "cable car": "grip",
  // india
  "rupee": "gandhi note",
  "upi payment": "scan sound",
  "traffic signal": "amber blink",
  "pressure cooker": "whistle count",
  "tiffin box": "tiered",
  "rangoli": "rice flour",
  "cricket match": "gully",
  "chai stall": "cutting glass",
  "vegetable market": "bargaining",
  "monsoon": "first showers",
  "street food": "cart wheel",
  "indian flag": "ashoka chakra",
  "indian railways": "chai vendor",
  "street vendor": "push cart",
  "kirana shop": "loose dal",
  "postbox": "red pillar",
  "toy train": "track curve",
  // entertainment
  "movie": "interval",
  "cartoon": "saturday morning",
  "newspaper": "morning doorstep",
  "radio": "tuning knob",
  "song": "refrain",
  "magic show": "hat trick",
  "comic book": "speech bubbles",
  "magazine": "glossy pages",
  "podcast": "earbuds walk",
  "video game": "respawn",
  "documentary": "narration",
  "web series": "binge",
  "short film": "credits scroll",
  "music video": "choreography",
  "advertisement": "jingle",
  "theatre": "curtain call",
  "stage show": "spotlight",
  "puppet show": "strings above",
  "streaming service": "autoplay",
  "movie ticket": "tear stub",
  "projector": "reel flicker",
  "speaker": "woofer",
  "talk show": "couch",
  "reality show": "voting lines",
  "award ceremony": "envelope",
  "sitcom": "laugh track",
  "circus": "big top",
  "clown": "red nose",
  "mime": "invisible box",
  "karaoke": "lyrics screen",
  // famous
  "harry potter": "scar",
  "spider-man": "web shooter",
  "batman": "cave",
  "superman": "cape",
  "mickey mouse": "ears",
  "doraemon": "pocket",
  "chhota bheem": "laddu power",
  "cinderella": "midnight",
  "mario": "pipes",
  "pikachu": "thunder cheeks",
  "virat kohli": "cover drive",
  "sachin tendulkar": "straight drive",
  "sherlock holmes": "magnifier",
  "tenali raman": "witty reply",
  "birbal": "emperor puzzle",
  "mowgli": "wolf pack",
  "winnie-the-pooh": "honey pot",
  "snow white": "apple bite",
  "sonic": "blue blur",
  "iron man": "arc reactor",
  "albert einstein": "relativity",
  "marie curie": "radium",
  "leonardo da vinci": "flying sketch",
  "kalpana chawla": "shuttle",
  "sunita williams": "spacewalk",
  "mary kom": "gloves",
  "neeraj chopra": "javelin gold",
  "akbar": "court",
  "chacha chaudhary": "lathi brain",
  "robin hood": "bow steal",
  "aladdin": "lamp",
  "pinocchio": "growing nose",
  "peter pan": "shadow",
  "rakshith volam": "divine protection",
  "nishanth payyavula": "first light",
  "vijay": "victory parade",
  "sunil": "sleep",
  "ritesh": "sacred rituals",
  "bunny": "carrot basket",
  // kitchen
  "refrigerator": "frost",
  "gas stove": "blue flame",
  "microwave oven": "beep",
  "mixer grinder": "whirr",
  "blender": "smoothie",
  "toaster": "pop up",
  "rice cooker": "keep warm",
  "rolling pin": "dough flat",
  "ladle": "serving",
  "grater": "knuckles",
  "mortar and pestle": "pound",
  "tawa": "flip",
  "colander": "drain",
  "frying pan": "sizzle",
  "saucepan": "simmer",
  // healthcare
  "bandage": "wrap",
  "cotton": "roll",
  "hand sanitizer": "gel squirt",
  "spectacles": "optician",
  "medicine": "dosage",
  "thermometer": "under tongue",
  "first-aid box": "red cross",
  "stethoscope": "chest piece",
  "syringe": "plunge",
  "ice pack": "numb",
  "wheelchair": "ramp",
  "inhaler": "puff",
  "crutches": "armpit grip",
  "walking stick": "rubber tip",
  "ointment": "thin layer",
  "cough syrup": "spoon cap",
  "prescription": "doctor scrawl",
  "eyedrops": "blink",
  "hearing aid": "whistle tune",
  // shopping
  "coin": "jingle",
  "banknote": "gandhi",
  "purse": "clasp",
  "atm": "pin pad",
  "piggy bank": "shake",
  "shopping cart": "wobbly wheel",
  "receipt": "thermal paper",
  "barcode": "beep",
  "price tag": "sticker",
  "discount coupon": "fine print",
  "gift card": "scratch",
  "cash register": "drawer ching",
  "shopping bag": "handles",
  "refund": "slip back",
  "change": "coins back",
  "invoice": "gst lines",
  // chores
  "sweeping": "broom strokes",
  "dusting": "cloth flick",
  "washing dishes": "suds",
  "making the bed": "corners",
  "watering plants": "can spout",
  "mopping": "bucket squeeze",
  "ironing": "steam hiss",
  "folding clothes": "neat stack",
  "vacuuming": "hum pull",
  "cooking": "simmer smell",
  // hobbies
  "gardening": "green thumb",
  "drawing": "sketch pad",
  "singing": "scale practice",
  "dancing": "mirror rehearsal",
  "yoga": "mat roll",
  "painting": "palette",
  "photography": "golden hour",
  "baking": "oven aroma",
  "knitting": "needles click",
  "origami": "paper crane",
  "pottery": "wheel spin",
  "meditation": "breath count",
  "trekking": "boots lace",
  "calligraphy": "nib dip",
  "astronomy": "star chart",
  "birdwatching": "binoculars",
  "fishing": "bait hook",
  "blogging": "draft folder",
  "embroidery": "hoop ring",
  // instruments
  "guitar": "fret",
  "piano": "pedal",
  "flute": "breath",
  "tabla": "syahi circle",
  "harmonium": "bellows",
  "violin": "chin rest",
  "drums": "stick roll",
  "sitar": "sympathetic strings",
  "veena": "gourd",
  "trumpet": "valve oil",
  "saxophone": "reed",
  "cello": "endpin",
  "banjo": "drum head",
  "xylophone": "mallets",
  "tambourine": "jingle tap",
  "dhol": "shoulder strap",
  "mouth organ": "hand cup",
  // travel
  "suitcase": "wheels pull",
  "map": "fold lines",
  "passport": "stamp page",
  "boarding pass": "gate number",
  "train ticket": "punch hole",
  "hotel room": "key card",
  "reservation": "booking id",
  "souvenir": "fridge magnet",
  "sleeping bag": "zip cocoon",
  "camping tent": "guy ropes",
  "jungle safari": "binocular view",
  "hill station": "mist road",
  "road trip": "dhaba stop",
  "layover": "transit gate",
  "itinerary": "day plan",
  "tourist guide": "flag leader",
  "currency exchange": "rate board",
  // toys
  "teddy bear": "button eyes",
  "doll": "tea party",
  "building blocks": "tower crash",
  "ball": "bounce echo",
  "kite": "thread spool",
  "balloon": "helium squeak",
  "puzzle": "edge pieces",
  "yo-yo": "sleep spin",
  "marbles": "dusty circle",
  "spinning top": "string pull",
  "puppet": "stick wiggle",
  "hula hoop": "waist whirl",
  "water gun": "summer ambush",
  "rocking horse": "stride creak",
  "bubble wand": "soapy film",
  "modelling clay": "mud pies",
  "slingshot": "aim fork",
  "jack-in-the-box": "crank pop",
  "kaleidoscope": "shard patterns",
  // emotions
  "happiness": "warm glow",
  "sadness": "heavy chest",
  "anger": "red mist",
  "fear": "goosebumps",
  "surprise": "gasp",
  "love": "flutter",
  "boredom": "ceiling stare",
  "shyness": "low eyes",
  "worry": "toss turn",
  "excitement": "bounce toes",
  "nervousness": "butterflies",
  "confusion": "tilted head",
  "pride": "chin up",
  "relief": "long exhale",
  "curiosity": "lean in",
  "jealousy": "green eyes",
  "embarrassment": "hot ears",
  "hope": "horizon gaze",
  "gratitude": "thankful heart",
  "loneliness": "empty bench",
  "panic": "short breaths",
  "amazement": "dropped jaw",
  "empathy": "walk in shoes",
  "grief": "dull ache",
  "nostalgia": "old photos",
  "melancholy": "rain window",
  "remorse": "apology draft",
  "bravery": "first step forward",
  "kindness": "warm gesture",
  "guilt": "sinking stomach",
  "delight": "clap hands",
  "awe": "wide eyes",
  "contentment": "slow smile",
  "determination": "grit teeth",
  "impatience": "foot tap",
  "disgust": "nose wrinkle",
  "suspicion": "narrowed eyes",
  "trust": "leap of faith",
  "anticipation": "edge of seat",
  "bliss": "quiet joy",
  "fury": "storm inside",
  "tenderness": "gentle touch",
});
